config/routes.rb
Rails.application.routes.draw do
  # deviseユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # ユーザー用
  root "homes#top"
  get "about" => "homes#about"
  get '/search', to: 'searches#search'
  
  scope module: :public do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users
      get   "unsubscribe"        => "users#unsubscribe"
      patch "withdraw"           => "users#withdraw"
    get :mypage, to: 'users#mypage'  
  end

  # devise管理者用
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用
  namespace :admin do
    resources :posts
    resources :users
    resources :dashboards, only: [:index]
  end
  
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>© 2025 シネマキュレーター</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <% if admin_signed_in? %>
        <%= link_to "シネマキュレーター", admin_dashboards_path, class: "navbar-brand" %>
        <span class="navbar-text me-auto ms-5">
          管理者モードです
        </span>
        
        <!-- ★ PC用ナビ（管理者ログイン時） -->
        <div class="header-nav-pc ms-auto">
          <ul class="navbar-nav d-flex flex-row">
              <li class="nav-item me-3">
              <%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %>
              </li>
              <li class="nav-item me-3">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
              </li>
          </ul>
        </div>

      <% elsif user_signed_in? %>

        <!-- ★ PC用ナビ（ユーザーログイン時） -->
        <%= link_to "シネマキュレーター", root_path, class: "navbar-brand" %>
        <span class="navbar-text me-auto ms-5">
            ようこそ <%= current_user.name %> さん
        </span>

        <!--div class="header-nav-pc d-flex align-items-center ms-auto"-->
        <%= render 'searches/form' %>
        <div class="header-nav-pc ms-auto">
          <ul class="navbar-nav d-flex flex-row">
            <li class="nav-item me-3">
              <%= link_to "投稿フォーム", new_post_path, class: "nav-link" %>
            </li>
            <li class="nav-item me-3">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item me-3">
              <%= link_to "マイページ", mypage_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>

      <% else %>
        
      <!-- ★ PC用ナビ（未ログイン時） -->
        <%= link_to "シネマキュレーター", root_path, class: "navbar-brand" %>

        <div class="header-nav-pc ms-auto">
          <ul class="navbar-nav d-flex flex-row">
            <li class="nav-item me-3">
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item me-3">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>

      <% end %>

      <!-- ★ ハンバーガーアイコン（全ログイン状態共通） -->
      <div id="hm-icon">
        <a href="#" class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

    </div>
  </nav>

    <!-- ★ SPメニュー本体 -->
  <div id="sp-menu">
    <ul class="list-unstyled mt-5">
      <% if admin_signed_in? %>
        <li><%= link_to "ユーザー一覧", admin_users_path %></li>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      <% elsif user_signed_in? %>
        <li><%= link_to "投稿フォーム", new_post_path %></li>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "マイページ", mypage_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineCura</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0987e8650e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <main class="container py-4">
      
      <% if notice.present? %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>

    <script>
      $(document).on('turbolinks:load', function() {
        $('.menu-trigger').on('click', function(event) {
          $(this).toggleClass('active');
          $('#sp-menu').fadeToggle();
          event.preventDefault();
        });
      });
    </script>


    <script src="js/jquery.min.js"></script>
    <script src="js/script.js"></script>
  </body>
</html>